### ISSUE TITLE
When I try to install, Windows active the Microsoft Defender SmartScreen

### ISSUE THREAD

**Issue by callmehanu** [eplatonoff/pilorama#19]
![image](https://user-images.githubusercontent.com/13230502/97900725-15a55500-1d09-11eb-8a52-7d84fdf2779c.png)

**Comment by gadswan** [comment]
Hey @callmehanu,

We officially published our app in the App Store, but publishing to Windows Market takes time. So, right now we have a completely stable and secure application, but without an approved Windows signature.

Here are the options:
- you could wait for the official publication of the app in Windows Store
or
- you could install it and use as it is

Have a nice day!

Thanks,
Sergey
