### ISSUE TITLE
Splitting Timer doesn't work

### ISSUE THREAD

**Issue by tom-davies** [eplatonoff/pilorama#27]
I'm running v 3.0.2 on Arch, and the "Split Timer to Sequence" option doesn't seem to work. No matter how it's set, the timer looks like this: 
![2021-04-12-122803_4480x1440_scrot](https://user-images.githubusercontent.com/170247/114387889-e681f200-9b8a-11eb-85d8-98afa91c5b2a.png)

**Comment by kartynnik** [comment]
Can reproduce this as well on a Debian derivative.

**Comment by kartynnik** [comment]
@tom-davies Upon inspecting the code, I've discovered that Pilorama initially starts in an "infinite mode" (in a loop) which disables SplitMode for some reason. However, you can switch to the "fixed amount of rounds" mode via "rotating" the timer as a dial with your mouse (the amount of rounds is displayed with newly added outer circles):
![image](https://user-images.githubusercontent.com/5329195/122808853-3e6f6000-d282-11eb-8d47-fdb5ff2cc21b.png)

I agree that this should be more easily discoverable (and as a stretch goal, the split mode should be made compatible with the default infinite one).

**Comment by tom-davies** [comment]
@kartynnik Thanks for finding that! I agree that it's not immediately obvious, and hope that we can find a way to make it more discoverable. I'm going to leave this open, in the hope that someone can work out how to make it more obvious
