### ISSUE TITLE
Incomplete AUR dependency list

### ISSUE THREAD

**Issue by linuxmobile** [eplatonoff/pilorama#34]
Hi dev. Pilorama in aur is outdated and with problems... 

If you can, try to update it!
Here a screenshot
![image](https://user-images.githubusercontent.com/10554636/152259312-0917f81a-2359-4a98-b5e2-b459b126a20f.png)

In other way (building process)

I already install all dependencies that you write. But it's look like something is missing...

![image](https://user-images.githubusercontent.com/10554636/152259405-bc11ec92-dac0-4883-be4b-237eb2107ebd.png)

**Comment by radioxoma** [comment]
* Package shall be flagged as outdated using AUR account, if it's really outdated, which is not the case.
* Please leave comment on [AUR package page](https://aur.archlinux.org/packages/pilorama-git), if you have questions to Archlinux maintainer.

`qt5-svg` has been added to 'depends' PKGBUILD section recently. Did latest PKGBUILD update solved your issue?
