### ISSUE TITLE
Pilorama archlinux install: Cannot stat pilorama-git/src/pilorama-git/src/assets/app_icons/icon_48x48x32.png

### ISSUE THREAD

**Issue by CaelumF** [eplatonoff/pilorama#5]
I really like the pomodoro timer, the idea of having a planned sequence of variable timers works very well for me :) and it looks really nice too.

When attempting to install the package from the AUR as described on the readme, the file above doesn't exist and the package() expects it to

**Comment by radioxoma** [comment]
Fixed in [AUR](https://aur.archlinux.org/cgit/aur.git/commit/PKGBUILD?h=pilorama-git&id=13528fafa8ccfd933e74499c5e4997792e0c9990) for now, but icon installation logic should be ported into [pilorama.pro](https://github.com/eplatonoff/pilorama/blob/master/src/pilorama.pro).
