### ISSUE TITLE
Strange icon mixups 

### ISSUE THREAD

**Issue by CaelumF** [eplatonoff/pilorama#6]
When I launch the application after building it per the instructions to clone and build, the icons appear to be mixed up somehow:

![image](https://user-images.githubusercontent.com/6132323/78452549-c8360c00-7683-11ea-896e-2e176bc2c60f.png)

Each time I launch it, the icons are mixed up in a different way:

![image](https://user-images.githubusercontent.com/6132323/78452563-dd129f80-7683-11ea-9c16-edfe104b4f72.png)

The application icon not displaying is probably because of #5

**Comment by radioxoma** [comment]
Please provide your GNU/Linux distribution name, Qt version and build log. `$ pikaur -S pilorama-git` worked out just fine for me today.

**Comment by vladtsm** [comment]
Unfortunately, we were not able to reproduce the issue on various Qt builds, operating systems and machines. The problem remains unknown. I'm closing the issue due to a long period of inactivity.  
If someone experiences the same problem with icon mixups please open a new issue.
