### ISSUE TITLE
Timer isn't working correctly

### ISSUE THREAD

**Issue by fxha** [eplatonoff/pilorama#7]
I like the app but I noticed that the timer is ticking too slow compared to the OS build-in clock. I added two splits with 25 and 5 minutes and kept the app running in the background (minimized). This unfortunately means that the app isn't usable because it cannot count correctly.

First try (time left):

- Pilorama: 15m
- OS timer: 26m

Second try:

- Pilorama: 3m
- OS timer: 18m

**Comment by eplatonoff** [comment]
Getting timer to sleep running as a background task was a known issue under macOS, but we’ve fixed it. Could you, please provide your OS name and version? Did you build app by yourself or used our build?

**Comment by fxha** [comment]
> Could you, please provide your OS name and version?

I tested it on both Windows 10 (1909) and Fedora 31 (kernel  5.6).

> Did you build app by yourself or used our build?

Yeah, I build from master branch on Linux and used the GitHub binaries on Windows.

**Comment by eplatonoff** [comment]
Ok, I guess I know what the problem is, will check it.

**Comment by fxha** [comment]
Thanks for your quick response. Now, the timer is way to fast (e.g. 5-10m ahead when using 25m split). Would it be possible to run the timer in the background and update the UI via interrupts? So that each second an event is called and the UI is updated but the timer keep running?

**Comment by eplatonoff** [comment]
In a way it already is in background. Previously we used synchronized with the animation timer. The second problem is possible related to timer accuracy –  I've set in today's commit precise type time, which should never time out earlier than expected (at least docs say so).  I've also add some other changes. Could you test the latest commit?
